---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: routers
  gather_facts: false
  connection: local
 
  tasks:
   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       commands:
         - show running-config  
     register: running_config
 
#github repository or local machine
   - name: SAVE OUTPUT TO BACKUP FOLDER
     copy:
       content: "{{ running_config.stdout[0] }}"
       dest: "https://github.com/EmmanuelaTurkson/netauto/tree/master/configurations/show_run_{{ inventory_hostname }}.txt"
