---
- name: SHOW IP EIGRP 
  hosts: R2

  tasks:
    - name: “Test EIGRP"
      ios_command:
        commands: "show ip route eigrp"
      register: output

    - name: print output
      debug:
        var: output.stdout_lines[0]
